plugins:
  - ./packages/yarn-plugin-ts-project-linker/bundles/@yarnpkg/plugin-ts-project-linker.js

packageExtensions:
  "vite@*":
    dependencies:
      supports-color: "*"
      bufferutil: "*"
  "vitest@*":
    dependencies:
      "@types/chai": "*"
  "debug@*":
    dependencies:
      supports-color: "*"