packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  vite@*:
    dependencies:
      bufferutil: "*"
      supports-color: "*"
  vitest@*:
    dependencies:
      "@types/chai": "*"


preferReuse: true
plugins:
  - ./packages/yarn-plugin-ts-project-linker/bundles/@yarnpkg/plugin-ts-project-linker.js
