name: Publish Package to npmjs

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  publish:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          scope: '@wroud'
          cache: 'yarn'

      - name: Install modules
        run: yarn

      - name: Build modules
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Publish to npm
        run: yarn npm publish
        working-directory: ./packages/di
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}